### ISSUE TITLE
Bulk expression data for comparison

### ISSUE THREAD

**Issue by sktowusuansah** [Roy-lab/scRNAseq_NetInference#5]
Hello, could you provide the pre-processed expression matrices used for inferring GRNs on bulk mouse and human samples? I had no problem retrieving the files for the scRNA-seq data, but that for the bulk samples seems quite difficult to get? Are you open to sharing it?

**Comment by sgmccalla** [comment]
Please find the yeast bulk dataset is available [here](https://bitbucket.org/roygroup/merlin-p_inferred_networks/src/master/yeast_networks/expression/) as part of the Roy group's previous publication "[A prior-based integrative framework for functional transcriptional regulatory network inference](https://academic-oup-com.ezproxy.library.wisc.edu/nar/article/45/4/e21/2333925?login=true&token=)." The other two datasets listed in [Supp Table S4](https://academic-oup-com.ezproxy.library.wisc.edu/g3journal/article/13/3/jkad004/6982776#supplementary-data) are actually part of a forthcoming paper that we are close to submitting. We anticipate the paper will be published this year but we will release the other two datasets as we are packaging that paper's supplementary supplementary data. We will have a preprint soon.
